### ISSUE TITLE
Add header rendering

### ISSUE THREAD

**Issue by gisostallenberg** [RonRademaker/Mailer#2]
Nice library.
It would be cool to be able to render more info in Twig, for example:

``` twig
{% block headers %}
To: "Some One" <some@one.net>
Subject: "My Subject"
Reply-To: <no-reply@my-domain.com>
{% endblock %}
```

**Comment by RonRademaker** [comment]
You can already render your `Subject` and the `To` header would conflict with the API. I do like the idea of being able to render headers in twig because it would allow a lot of flexibility. 

I think the potentially conflicting headers (just Subject, To and From as far as I can see now) should trigger a notice if used in a conflicting situation (with the current API taking precedence).

**Comment by RonRademaker** [comment]
I looked into this but unfortunately it appears Swift_Message doesn't have a (clear) API to set headers. Would you happen to know if there's some way around that? 

Another option would be to support only a limited set of headers, for which setters are available.

**Comment by gisostallenberg** [comment]
It is something like this:

``` php
$message->getHeaders()->get('Reply-To')->setValue('<no-reply@my-domain.com>');
```

See http://swiftmailer.org/docs/headers.html
What is missing?

**Comment by RonRademaker** [comment]
Ah, thanks, I missed that. I was looking for something like `setHeader` or `addHeader`. IMO setting stuff through getters smells a bit, but it'll work.

**Comment by gisostallenberg** [comment]
It is just object oriented. All you get from `$message->getHeaders()->get('Reply-To')` is an object that happens to have a setValue method. Because it is referenced it gets updated in the Swift_Message also.

**Comment by RonRademaker** [comment]
I get why it works, I just don't like it very much  😉

**Comment by gisostallenberg** [comment]
This issue is stale
